// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD-ye_A8PswRzcfpEiLqghOGRcu8UfL7Q',
    appId: '1:777337977048:web:7b2f4c78224e77409a3fad',
    messagingSenderId: '777337977048',
    projectId: 'daily-planner-593d8',
    authDomain: 'daily-planner-593d8.firebaseapp.com',
    storageBucket: 'daily-planner-593d8.firebasestorage.app',
    measurementId: 'G-5126GQMZRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIQJb6DHJ6WTw8Vwd04Vjf5Z380uIHWkw',
    appId: '1:777337977048:android:792f4ba50ada24169a3fad',
    messagingSenderId: '777337977048',
    projectId: 'daily-planner-593d8',
    storageBucket: 'daily-planner-593d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC246wvcV72m_wB0bmlvZ-m9DTRpbVs7Tc',
    appId: '1:777337977048:ios:b6ffdf110b4f06bb9a3fad',
    messagingSenderId: '777337977048',
    projectId: 'daily-planner-593d8',
    storageBucket: 'daily-planner-593d8.firebasestorage.app',
    androidClientId: '777337977048-vf0nr3plk0e3k5h11u4r1gqsqrbm9o2u.apps.googleusercontent.com',
    iosClientId: '777337977048-irs04ai9uj7jabkuvt1kv0dv4rj311bt.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyPlanner',
  );

}